---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# SpatialClustering

<!-- badges: start -->
<!-- badges: end -->

SpatialClustering provides tools and data to reproduce the analyses from the article “Comparative Multivariate Analysis of Spatial Clustering in Neanderthal and Anatomically Modern Human Occupations”.
The project applies cluster modeling to archaeological spatial data to explore differences in camp organization in Middle and Upper Paleolithic during the Late Pleistocene.

## Installation

You can install the development version of SpatialClustering from [GitHub]((https://github.com/AMerino-Pelaz/SpatialClustering)) with:

``` r
# install.packages("pak")
pak::pak("AMerino-Pelaz/SpatialClustering")
```

## Contents

- Scripts for spatial clustering analyses and regression models  
- Archaeological datasets from 21 Paleolithic assemblages  
- Figures and outputs associated with the publication

## Citation

If you use this repository or its code in your work, please cite:

[dataset] Merino-Pelaz, A., Cobo-Sánchez, L., 2025. Dataset associated with: “Comparative Multivariate Analysis of Spatial Clustering in Neanderthal and Anatomically Modern Human Occupations”. OSF. https://doi.org/10.17605/OSF.IO/ZH5BK

